### ISSUE TITLE
Update README - Replace all gifs

### ISSUE THREAD

**Issue by rachidcalazans** [rachidcalazans/chid#39]
All gifs are from the older version, which uses rake based. Now are Command based using a Gem. Is necessary to make gifs using the new way.

**Comment by ParisaTork** [comment]
Hi, I'd like to assign myself to this issue. Please can you give more details on how you would like the gifs to be? :)

**Comment by rachidcalazans** [comment]
Hi @ParisaTork I used this app **http://recordit.co** .

The step I used was:
1- Record my terminal screen using the features
2- Get the link generated by the **recordit** app and put on README.md

**Comment by ParisaTork** [comment]
Hey @rachidcalazans, I'm having some setup issues. When I installed the chid gem and ran chid in the terminal, I get 'bash: command not found'. Is there anything I can do about this? :)

**Comment by rachidcalazans** [comment]
@ParisaTork Which step did you try?

Steps you need: 
1- gem install chid
2- chid init

**Comment by ParisaTork** [comment]
@rachidcalazans I tried both 1 and 2. Both return 'bash: command not found' 😯

**Comment by rachidcalazans** [comment]
@ParisaTork Please, post here a gif of your steps and the error?

**Comment by ParisaTork** [comment]
Hey @rachidcalazans, 
Here's the [gif link](https://imgur.com/GAiGKtQ) :)

I've tried:
- chid init (globally)
- chid -h (globally)
- chid init (while in chid directory)
- chid -h (while in chid directory)

**Comment by rachidcalazans** [comment]
@ParisaTork It's weird. I've tried again here and seems fine.

If you download the project, you can try use this command inside the project:

`ruby -Ilib bin/chid [COMMAND]`

This command is explained on [contributing file](https://github.com/rachidcalazans/chid/blob/master/CONTRIBUTING.md)

**Comment by ParisaTork** [comment]
Hey @rachidcalazans, I just posted a trial gif #40 to test if you like this style of gif. Please let me know if you would like any improvements. If it's fine, then I will go ahead and make all the other gifs like this trial gif.

**Comment by ParisaTork** [comment]
You can see the gif in action here: https://github.com/ParisaTork/chid/blob/master/README.md

**Comment by rachidcalazans** [comment]
@ParisaTork Hey man, nice. For the gif you created, you can show more features like we have today. And the other gifs should be updated too, because is showing using the old way.

**Comment by ParisaTork** [comment]
Thanks @rachidcalazans. Just to let you know, issue #39 is complete, so now, all the gifs have been changed. Please see PR #40 for more info. Please let me know if you would like any improvements :)

**Comment by rachidcalazans** [comment]
Issue done.
